version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.velocitypowered:velocity-api
    versions:
    - 2.0.0-SNAPSHOT
