version: "3"

services:
  redis:
    image: redis
    volumes:
      - ./data/redis/:/data
  mariadb:
    image: mariadb
    volumes:
      - ./data/redis/:/var/lib/mysql
    env_file:
      - db-config/db.env
  velocity:
    image: itzg/bungeecord
    ports:
      - 25565:25577
    env_file:
      - velocity-config/velocity.env
    environment:
      TYPE: "VELOCITY"
      ENABLE_RCON: "FALSE"
    secrets:
      - velocity_secret
    volumes:
      - ./data/velocity:/server
      - ./velocity-config/plugins:/plugins
      - ./velocity-config/:/config

  lobby:
    image: itzg/minecraft-server
    secrets:
      - velocity_secret
    environment:
      CFG_SERVER_NAME: "lobby"
    env_file:
      - velocity-config/velocity.env
      - mc-config/mc.env
    volumes:
      - ./data/lobby:/data
      - ./mc-config:/config

  mc-1:
    image: itzg/minecraft-server
    secrets:
      - velocity_secret
    environment:
      CFG_SERVER_NAME: "mc1"
    env_file:
      - velocity-config/velocity.env
      - mc-config/mc.env
    volumes:
      - ./data/mc-1:/data
      - ./mc-config:/config

  mc-2:
    image: itzg/minecraft-server
    secrets:
      - velocity_secret
    environment:
      CFG_SERVER_NAME: "mc-2"
    env_file:
      - velocity-config/velocity.env
      - mc-config/mc.env
    volumes:
      - ./data/mc-2:/data
      - ./mc-config:/config

secrets:
  velocity_secret:
    file: velocity-config/velocity_secret